name: update formula
on:
  schedule:
    - cron:  '*/5 * * * *'
jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:

    - name: Inspect recent Jenkins builds
      shell: bash
      run: |
        sh ./lib/jenkins.rb
    
    - name: Update Formula
      shell: bash
      run: |
        git add Formula/maven-snapshot.rb last-build.txt
        git commit -m "Update to latest Maven snapshot"
        git push origin master